version: '3.8'

services:
  meddb:
    container_name: meddb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: meddb
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
      - ./db/db-scripts:/usr/local/database
    ports:
      - "5432:5432"
    networks:
      - medapp-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gerald@gmatech.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - medapp-network
      
  vault:
    container_name: vault
    image: hashicorp/vault:latest
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
      # VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - ./vault/data:/vault/data
      - ./vault/logs:/etc/vault/logs
      # - ./vault/config:/vault/config
    ports:
      - "8200:8200/tcp"
    cap_add:
      - IPC_LOCK
    # entrypoint: "vault server -config=/vault/config/config.hcl"
    entrypoint: "vault server -dev"
    networks:
      - medapp-network

networks:
  medapp-network:
    driver: bridge
